version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: agentchain-postgres
    environment:
      POSTGRES_DB: agentchain
      POSTGRES_USER: agentchain
      POSTGRES_PASSWORD: agentchain_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: agentchain-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agentchain-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://agentchain:agentchain_password@postgres:5432/agentchain
      REDIS_URL: redis://redis:6379
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agentchain-frontend
    environment:
      VITE_API_URL: http://localhost:4000
      VITE_WS_URL: ws://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  postgres_data: